# BANNER
banner:
  charset: UTF-8
  # Banner file location.
  location: classpath:banner.txt 
#Properties
spring:
  thymeleaf:
    cache: true
    content-type: text/html; charset=utf-8
    check-template: true
    enabled: true